name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Message that will be displayed on users'' first issue'
        pr-message: 'Message that will be displayed on users'' first pr'  - name: Upload artifact
  uses: actions/upload-artifact@v1.0.0
  with:
    # Artifact name
    name: 
    # Directory containing files to upload
    path: 
